"""initial schema

Revision ID: 27c89ad532be
Revises: 
Create Date: 2026-09-21 02:49:22.557734
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '27c89ad532be'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emoticons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('source_site', sa.String(length=50), nullable=True),
    sa.Column('original_path', sa.String(length=300), nullable=True),
    sa.Column('processed_path', sa.String(length=300), nullable=False),
    sa.Column('preview_path', sa.String(length=300), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('image_dhash', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emoticons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emoticons_image_dhash'), ['image_dhash'], unique=False)
        batch_op.create_index(batch_op.f('ix_emoticons_image_sha256'), ['image_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_emoticons_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_emoticons_source_url'), ['source_url'], unique=False)

    op.create_table('emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emotions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emotions_tag'), ['tag'], unique=True)

    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keywords_value'), ['value'], unique=True)

    op.create_table('app_emojis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emoticon_id', sa.Integer(), nullable=False),
    sa.Column('emoji_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji_name', sa.String(length=32), nullable=False),
    sa.Column('animated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['emoticon_id'], ['emoticons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emoji_id'),
    sa.UniqueConstraint('emoticon_id')
    )
    op.create_table('emoticon_emotions',
    sa.Column('emoticon_id', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emoticon_id'], ['emoticons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('emoticon_id', 'emotion_id')
    )
    op.create_table('emoticon_keywords',
    sa.Column('emoticon_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emoticon_id'], ['emoticons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('emoticon_id', 'keyword_id')
    )
    op.create_table('emotion_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_id'], ['emotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emotion_id', 'related_id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('emoticon_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['emoticon_id'], ['emoticons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'emoticon_id')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('guild_emojis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emoticon_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['emoticon_id'], ['emoticons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emoticon_id', 'guild_id')
    )
    with op.batch_alter_table('guild_emojis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guild_emojis_guild_id'), ['guild_id'], unique=False)

    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emoticon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('context', sa.String(length=20), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['emoticon_id'], ['emoticons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_usage_user_time', ['user_id', 'used_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_user_time')
        batch_op.drop_index(batch_op.f('ix_usage_logs_user_id'))

    op.drop_table('usage_logs')
    with op.batch_alter_table('guild_emojis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_emojis_guild_id'))

    op.drop_table('guild_emojis')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))

    op.drop_table('favorites')
    op.drop_table('emotion_relations')
    op.drop_table('emoticon_keywords')
    op.drop_table('emoticon_emotions')
    op.drop_table('app_emojis')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_value'))

    op.drop_table('keywords')
    with op.batch_alter_table('emotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emotions_tag'))

    op.drop_table('emotions')
    with op.batch_alter_table('emoticons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emoticons_source_url'))
        batch_op.drop_index(batch_op.f('ix_emoticons_name'))
        batch_op.drop_index(batch_op.f('ix_emoticons_image_sha256'))
        batch_op.drop_index(batch_op.f('ix_emoticons_image_dhash'))

    op.drop_table('emoticons')
    # ### end Alembic commands ###
